import React, { createContext, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'hi' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.triage': 'Triage',
    'nav.overview': 'Overview',
    'nav.doctors': 'Doctors',
    'nav.patients': 'Patients',
    'nav.nurses': 'Nurses',
    'nav.profile': 'Profile',
    'nav.changePassword': 'Change Password',
    'nav.logout': 'Logout',
    'nav.about': 'About',
    'nav.ethics': 'Ethics',
    'nav.regulations': 'Regulations',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'home.portal': 'MediTriage Public Portal',
    'home.heroTitle': 'Safe and Regulated Clinical Triage',
    'home.heroSubtitle':
      'This landing page provides policy transparency and secure staff access. Clinical modules become available only after authenticated login.',
    'home.aboutBody':
      'MediTriage assists hospitals with AI-supported patient triage, workflow coordination, and clinician decision support for urgent care settings.',
    'home.ethicsBody':
      'The platform is designed for clinical transparency, bias monitoring, traceable recommendations, and human-in-the-loop oversight in all triage decisions.',
    'home.regulationsBody':
      'Access is restricted to authenticated staff accounts. Patient and staff actions are expected to comply with hospital policy and applicable healthcare data regulations.',
    'footer.copyright': '© 2026 MediTriage AI. All rights reserved.',
    'footer.tagline': 'Intelligent Healthcare Management System',

    'common.backToDoctors': 'Back to Doctors',
    'common.backToNurses': 'Back to Nurses',
    'common.backToPatients': 'Back to Patients',
    'common.loadingDoctor': 'Loading doctor details...',
    'common.loadingNurse': 'Loading nurse details...',
    'common.loadingPatient': 'Loading patient details...',
    'common.doctorNotFound': 'Doctor not found',
    'common.nurseNotFound': 'Nurse not found',
    'common.patientNotFound': 'Patient not found',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.found': 'Found',
    'common.trySearch': 'Try adjusting your search query',
    'common.tryAgain': 'Please try again or contact support',
    'common.notSet': 'Not set',
    'common.na': 'N/A',

    'doctor.id': 'Doctor ID',
    'doctor.department': 'Department',
    'doctor.specialization': 'Specialization',
    'doctor.experience': 'Experience',
    'doctor.years': 'years',
    'doctor.license': 'License Number',
    'doctor.qualifications': 'Qualifications',
    'doctor.contact': 'Contact',
    'doctor.unnamed': 'Unnamed Doctor',
    'doctor.noQualifications': 'No qualifications listed',

    'nurse.id': 'Nurse ID',
    'nurse.department': 'Department',
    'nurse.shift': 'Shift',
    'nurse.license': 'License Number',
    'nurse.qualifications': 'Qualifications',
    'nurse.contact': 'Contact',
    'nurse.unnamed': 'Unnamed Nurse',
    'nurse.noQualifications': 'No qualifications listed',

    'patient.id': 'Patient ID',
    'patient.age': 'Age',
    'patient.gender': 'Gender',
    'patient.contact': 'Contact',
    'patient.bloodGroup': 'Blood Group',
    'patient.recommendedDepartment': 'Recommended Department',
    'patient.medicalInfo': 'Medical Information',
    'patient.previousConditions': 'Previous Medical Conditions',
    'patient.allergies': 'Allergies',
    'patient.currentMeds': 'Current Medications',
    'patient.noConditions': 'No conditions recorded',
    'patient.noAllergies': 'No allergies recorded',
    'patient.noMeds': 'No medications recorded',
    'patient.guardian': 'Guardian/Emergency Contact',
    'patient.name': 'Name',
    'patient.recentTriages': 'Recent Triage Assessments',
    'patient.noTriages': 'No triage assessments yet',
    'patient.department': 'Department',
    'patient.symptoms': 'Symptoms',
    'patient.riskScore': 'Risk Score',
    'patient.unnamed': 'Unnamed Patient',
    'patient.viewReports': 'View Test Reports and Health Insights',
    'patient.reportSub': 'Comprehensive health metrics and reports',
    'doctors.title': 'Doctor Directory',
    'doctors.subtitle': 'Search and view available doctors',
    'doctors.searchPlaceholder': 'Search by name, department, qualification, or ID...',
    'doctors.loading': 'Loading doctors...',
    'doctors.total': 'Total Doctors',
    'doctors.empty': 'No doctors found',
    'doctors.itemsPlural': 'doctors',
    'doctors.itemSingle': 'doctor',
    'doctors.experienceSuffix': 'experience',
    'doctors.licensed': 'Licensed',
    'doctors.noLicense': 'No License Info',
    'nurses.title': 'Nurse Directory',
    'nurses.subtitle': 'Manage nurse assignments and patient care',
    'nurses.searchPlaceholder': 'Search by name, department, or ID...',
    'nurses.loading': 'Loading nurses...',
    'nurses.total': 'Total Nurses',
    'nurses.empty': 'No nurses found',
    'nurses.itemsPlural': 'nurses',
    'nurses.itemSingle': 'nurse',
    'nurses.licensed': 'Licensed',
    'nurses.noLicense': 'No License Info',
    'patients.title': 'Patient Records',
    'patients.subtitle': 'Search and view patient information',
    'patients.searchPlaceholder': 'Search by name, ID, or blood type...',
    'patients.loading': 'Loading patients...',
    'patients.total': 'Total Patients',
    'patients.empty': 'No patients found',
    'patients.itemsPlural': 'patients',
    'patients.itemSingle': 'patient',
    'patients.bloodType': 'Blood Type',
    'patients.notSpecified': 'Not specified',
    'triage.title': 'Patient Triage',
    'triage.subtitle': 'AI-powered patient assessment and department routing',
    'triage.basicInfo': 'Basic Information',
    'triage.medicalInfo': 'Medical Information',
    'triage.vitals': 'Vital Signs (if available)',
    'triage.guardian': 'Guardian/Emergency Contact',
    'triage.submit': 'Perform AI Triage Assessment',
    'triage.patientInfo': 'Patient Information',
    'triage.patientInfoDesc': 'Enter patient details for AI-based triage assessment',
    'triage.fullName': 'Full Name',
    'triage.fullNamePlaceholder': 'John Doe',
    'triage.age': 'Age',
    'triage.gender': 'Gender',
    'triage.genderMale': 'Male',
    'triage.genderFemale': 'Female',
    'triage.genderOther': 'Other',
    'triage.contactNumber': 'Contact Number',
    'triage.currentSymptoms': 'Current Symptoms',
    'triage.symptomsPlaceholder': 'Enter multiple symptoms (comma, semicolon, or new line separated)',
    'triage.symptomsExample': 'Example: chest pain, shortness of breath, dizziness, nausea',
    'triage.previousConditions': 'Previous Medical Conditions',
    'triage.conditionsPlaceholder': 'List any previous medical conditions, allergies, or ongoing treatments...',
    'triage.doctorsFollowing': 'Doctors Following (comma-separated IDs)',
    'triage.bloodPressure': 'Blood Pressure',
    'triage.heartRate': 'Heart Rate (bpm)',
    'triage.temperature': 'Temperature (F)',
    'triage.respiratoryRate': 'Respiratory Rate (/min)',
    'triage.oxygenSaturation': 'Oxygen Saturation (%)',
    'triage.guardianName': 'Guardian Name',
    'triage.guardianNamePlaceholder': 'Jane Doe',
    'triage.guardianContact': 'Guardian Contact',
    'triage.processing': 'Processing Triage...',
    'triage.resultTitle': 'Triage Assessment Complete',
    'triage.resultSubtitle': 'AI-generated risk assessment and department recommendation',
    'triage.riskLevel': 'Risk Level',
    'triage.riskSuffix': 'Risk',
    'triage.recommendedDepartment': 'Recommended Department',
    'triage.clinicalReasoning': 'Clinical Reasoning',
    'triage.requiredTests': 'Required Tests and Procedures',
    'triage.viewPatients': 'View Patient Records',
    'triage.error.required': 'Please fill in all required fields',
    'triage.error.symptomRequired': 'Please enter at least one symptom',
    'triage.error.failed': 'Failed to process triage',
    'triage.success.complete': 'Triage assessment completed successfully!',
    'triage.success.reasoningDefault': 'AI triage completed successfully.',
    'triage.risk.medium': 'Medium',
    'triage.department.general': 'General Medicine',
    'triage.symptom.chestPain': 'Chest Pain',
    'triage.symptom.breathing': 'Difficulty Breathing',
    'triage.symptom.headache': 'Severe Headache',
    'triage.symptom.abdominal': 'Abdominal Pain',
    'triage.symptom.fever': 'Fever',
    'triage.symptom.nausea': 'Nausea',
    'triage.symptom.dizziness': 'Dizziness',
    'triage.symptom.confusion': 'Confusion',
    'triage.symptom.loc': 'Loss of Consciousness',
    'triage.condition.diabetes': 'Diabetes',
    'triage.condition.hypertension': 'Hypertension',
    'triage.condition.heartDisease': 'Heart Disease',
    'triage.condition.asthma': 'Asthma',
    'triage.condition.cancer': 'Cancer',
    'triage.condition.kidneyDisease': 'Kidney Disease',
    'triage.condition.none': 'None',
    'overview.title': 'Hospital Overview',
    'overview.subtitle': 'Real-time hospital status and resource monitoring',
    'overview.loading': 'Loading hospital data...',
    'overview.errorLoad': 'Failed to load hospital data. Please try again.',
    'overview.hospitalStatus': 'Hospital Status',
    'overview.totalPatients': 'Total Patients',
    'overview.currentlyInHospital': 'Currently in hospital',
    'overview.onDuty': 'On duty',
    'overview.freeBeds': 'Free Beds',
    'overview.outOf': 'Out of',
    'overview.bedStatus': 'Bed Status',
    'overview.totalBeds': 'Total Beds',
    'overview.occupied': 'occupied',
    'overview.departments': 'Departments',
    'overview.bedsAvailable': 'beds available',
    'overview.bedsOccupied': 'beds occupied',
    'overview.live': 'Live',
    'overview.staff': 'Staff',
    'overview.available': 'Available',
    'overview.status.normal': 'Normal',
    'overview.status.busy': 'Busy',
    'overview.status.critical': 'Critical',
    'overview.bed.available': 'Available',
    'overview.bed.low': 'Low',
    'overview.bed.critical': 'Critical',
  },
  hi: {
    'nav.home': 'होम',
    'nav.triage': 'ट्रायेज',
    'nav.overview': 'अवलोकन',
    'nav.doctors': 'डॉक्टर्स',
    'nav.patients': 'मरीज',
    'nav.nurses': 'नर्सेस',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.changePassword': 'पासवर्ड बदलें',
    'nav.logout': 'लॉगआउट',
    'nav.about': 'परिचय',
    'nav.ethics': 'नैतिकता',
    'nav.regulations': 'नियम',
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'home.portal': 'MediTriage सार्वजनिक पोर्टल',
    'home.heroTitle': 'सुरक्षित और विनियमित क्लिनिकल ट्रायेज',
    'home.heroSubtitle': 'यह पेज नीति पारदर्शिता और सुरक्षित स्टाफ एक्सेस देता है। क्लिनिकल मॉड्यूल लॉगिन के बाद ही उपलब्ध होते हैं।',
    'home.aboutBody': 'MediTriage अस्पतालों को AI-सहायता प्राप्त ट्रायेज और क्लिनिकल निर्णय सहयोग देता है।',
    'home.ethicsBody': 'प्लेटफ़ॉर्म पारदर्शिता, बायस मॉनिटरिंग और मानव निगरानी को ध्यान में रखकर बनाया गया है।',
    'home.regulationsBody': 'एक्सेस केवल प्रमाणित स्टाफ के लिए है और डेटा उपयोग अस्पताल व स्वास्थ्य नियमों के अनुसार होना चाहिए।',
    'footer.copyright': '© 2026 MediTriage AI. सर्वाधिकार सुरक्षित।',
    'footer.tagline': 'स्मार्ट हेल्थकेयर प्रबंधन प्रणाली',
    'common.backToDoctors': 'डॉक्टर्स पर वापस',
    'common.backToNurses': 'नर्सेस पर वापस',
    'common.backToPatients': 'मरीजों पर वापस',
    'common.loadingDoctor': 'डॉक्टर विवरण लोड हो रहा है...',
    'common.loadingNurse': 'नर्स विवरण लोड हो रहा है...',
    'common.loadingPatient': 'मरीज विवरण लोड हो रहा है...',
    'common.doctorNotFound': 'डॉक्टर नहीं मिला',
    'common.nurseNotFound': 'नर्स नहीं मिली',
    'common.patientNotFound': 'मरीज नहीं मिला',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.found': 'मिले',
    'common.trySearch': 'खोज को बदलकर फिर प्रयास करें',
    'common.tryAgain': 'कृपया फिर प्रयास करें या सपोर्ट से संपर्क करें',
    'common.notSet': 'सेट नहीं',
    'common.na': 'उपलब्ध नहीं',
    'doctor.id': 'डॉक्टर आईडी',
    'doctor.department': 'विभाग',
    'doctor.specialization': 'विशेषज्ञता',
    'doctor.experience': 'अनुभव',
    'doctor.years': 'वर्ष',
    'doctor.license': 'लाइसेंस नंबर',
    'doctor.qualifications': 'योग्यताएं',
    'doctor.contact': 'संपर्क',
    'doctor.unnamed': 'अनाम डॉक्टर',
    'doctor.noQualifications': 'कोई योग्यता सूचीबद्ध नहीं',
    'nurse.id': 'नर्स आईडी',
    'nurse.department': 'विभाग',
    'nurse.shift': 'शिफ्ट',
    'nurse.license': 'लाइसेंस नंबर',
    'nurse.qualifications': 'योग्यताएं',
    'nurse.contact': 'संपर्क',
    'nurse.unnamed': 'अनाम नर्स',
    'nurse.noQualifications': 'कोई योग्यता सूचीबद्ध नहीं',
    'patient.id': 'मरीज आईडी',
    'patient.age': 'आयु',
    'patient.gender': 'लिंग',
    'patient.contact': 'संपर्क',
    'patient.bloodGroup': 'ब्लड ग्रुप',
    'patient.recommendedDepartment': 'सुझाया गया विभाग',
    'patient.medicalInfo': 'चिकित्सा जानकारी',
    'patient.previousConditions': 'पिछली चिकित्सा स्थितियां',
    'patient.allergies': 'एलर्जी',
    'patient.currentMeds': 'वर्तमान दवाएं',
    'patient.noConditions': 'कोई स्थिति दर्ज नहीं',
    'patient.noAllergies': 'कोई एलर्जी दर्ज नहीं',
    'patient.noMeds': 'कोई दवा दर्ज नहीं',
    'patient.guardian': 'अभिभावक/आपातकालीन संपर्क',
    'patient.name': 'नाम',
    'patient.recentTriages': 'हाल के ट्रायेज आकलन',
    'patient.noTriages': 'अभी तक कोई ट्रायेज आकलन नहीं',
    'patient.department': 'विभाग',
    'patient.symptoms': 'लक्षण',
    'patient.riskScore': 'जोखिम स्कोर',
    'patient.unnamed': 'अनाम मरीज',
    'patient.viewReports': 'टेस्ट रिपोर्ट और हेल्थ इनसाइट्स देखें',
    'patient.reportSub': 'व्यापक स्वास्थ्य मेट्रिक्स और रिपोर्ट',
    'doctors.title': 'डॉक्टर निर्देशिका',
    'doctors.subtitle': 'डॉक्टर्स को खोजें और देखें',
    'doctors.searchPlaceholder': 'नाम, विभाग, योग्यता या आईडी से खोजें...',
    'doctors.loading': 'डॉक्टर्स लोड हो रहे हैं...',
    'doctors.total': 'कुल डॉक्टर',
    'doctors.empty': 'कोई डॉक्टर नहीं मिला',
    'doctors.itemsPlural': 'डॉक्टर्स',
    'doctors.itemSingle': 'डॉक्टर',
    'doctors.experienceSuffix': 'अनुभव',
    'doctors.licensed': 'लाइसेंस प्राप्त',
    'doctors.noLicense': 'लाइसेंस जानकारी नहीं',
    'nurses.title': 'नर्स निर्देशिका',
    'nurses.subtitle': 'नर्स असाइनमेंट और रोगी देखभाल प्रबंधन',
    'nurses.searchPlaceholder': 'नाम, विभाग या आईडी से खोजें...',
    'nurses.loading': 'नर्सेस लोड हो रही हैं...',
    'nurses.total': 'कुल नर्सेस',
    'nurses.empty': 'कोई नर्स नहीं मिली',
    'nurses.itemsPlural': 'नर्सेस',
    'nurses.itemSingle': 'नर्स',
    'nurses.licensed': 'लाइसेंस प्राप्त',
    'nurses.noLicense': 'लाइसेंस जानकारी नहीं',
    'patients.title': 'रोगी रिकॉर्ड्स',
    'patients.subtitle': 'रोगी जानकारी खोजें और देखें',
    'patients.searchPlaceholder': 'नाम, आईडी या ब्लड ग्रुप से खोजें...',
    'patients.loading': 'रोगी लोड हो रहे हैं...',
    'patients.total': 'कुल रोगी',
    'patients.empty': 'कोई रोगी नहीं मिला',
    'patients.itemsPlural': 'रोगी',
    'patients.itemSingle': 'रोगी',
    'patients.bloodType': 'ब्लड टाइप',
    'patients.notSpecified': 'निर्दिष्ट नहीं',
    'triage.title': 'मरीज ट्रायेज',
    'triage.subtitle': 'AI आधारित मरीज मूल्यांकन और विभाग रूटिंग',
    'triage.basicInfo': 'मूल जानकारी',
    'triage.medicalInfo': 'चिकित्सा जानकारी',
    'triage.vitals': 'वाइटल संकेत (यदि उपलब्ध)',
    'triage.guardian': 'अभिभावक/आपातकालीन संपर्क',
    'triage.submit': 'AI ट्रायेज मूल्यांकन करें',
    'triage.patientInfo': 'मरीज जानकारी',
    'triage.patientInfoDesc': 'AI ट्रायेज मूल्यांकन के लिए मरीज विवरण दर्ज करें',
    'triage.fullName': 'पूरा नाम',
    'triage.fullNamePlaceholder': 'जॉन डो',
    'triage.age': 'आयु',
    'triage.gender': 'लिंग',
    'triage.genderMale': 'पुरुष',
    'triage.genderFemale': 'महिला',
    'triage.genderOther': 'अन्य',
    'triage.contactNumber': 'संपर्क नंबर',
    'triage.currentSymptoms': 'वर्तमान लक्षण',
    'triage.symptomsPlaceholder': 'कई लक्षण दर्ज करें (कॉमा, सेमीकोलन, या नई पंक्ति से अलग करें)',
    'triage.symptomsExample': 'उदाहरण: सीने में दर्द, सांस फूलना, चक्कर, मितली',
    'triage.previousConditions': 'पिछली चिकित्सा स्थितियां',
    'triage.conditionsPlaceholder': 'पिछली बीमारियां, एलर्जी, या उपचार दर्ज करें...',
    'triage.doctorsFollowing': 'फ़ॉलो करने वाले डॉक्टर (कॉमा से अलग आईडी)',
    'triage.bloodPressure': 'ब्लड प्रेशर',
    'triage.heartRate': 'हार्ट रेट (bpm)',
    'triage.temperature': 'तापमान (F)',
    'triage.respiratoryRate': 'श्वसन दर (/मिनट)',
    'triage.oxygenSaturation': 'ऑक्सीजन सैचुरेशन (%)',
    'triage.guardianName': 'अभिभावक नाम',
    'triage.guardianNamePlaceholder': 'जेन डो',
    'triage.guardianContact': 'अभिभावक संपर्क',
    'triage.processing': 'ट्रायेज प्रोसेस हो रहा है...',
    'triage.resultTitle': 'ट्रायेज मूल्यांकन पूर्ण',
    'triage.resultSubtitle': 'AI आधारित जोखिम मूल्यांकन और विभाग सुझाव',
    'triage.riskLevel': 'जोखिम स्तर',
    'triage.riskSuffix': 'जोखिम',
    'triage.recommendedDepartment': 'सुझाया गया विभाग',
    'triage.clinicalReasoning': 'क्लिनिकल कारण',
    'triage.requiredTests': 'आवश्यक परीक्षण और प्रक्रियाएं',
    'triage.viewPatients': 'मरीज रिकॉर्ड देखें',
    'triage.error.required': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'triage.error.symptomRequired': 'कृपया कम से कम एक लक्षण दर्ज करें',
    'triage.error.failed': 'ट्रायेज प्रोसेस विफल हुआ',
    'triage.success.complete': 'ट्रायेज मूल्यांकन सफलतापूर्वक पूर्ण हुआ!',
    'triage.success.reasoningDefault': 'AI ट्रायेज सफलतापूर्वक पूरा हुआ।',
    'triage.risk.medium': 'मध्यम',
    'triage.department.general': 'जनरल मेडिसिन',
    'overview.title': 'अस्पताल अवलोकन',
    'overview.subtitle': 'रियल-टाइम अस्पताल स्थिति और संसाधन मॉनिटरिंग',
    'overview.loading': 'अस्पताल डेटा लोड हो रहा है...',
    'overview.errorLoad': 'अस्पताल डेटा लोड नहीं हुआ। कृपया फिर प्रयास करें।',
    'overview.hospitalStatus': 'अस्पताल स्थिति',
    'overview.totalPatients': 'कुल मरीज',
    'overview.currentlyInHospital': 'वर्तमान में अस्पताल में',
    'overview.onDuty': 'ड्यूटी पर',
    'overview.freeBeds': 'खाली बेड',
    'overview.outOf': 'में से',
    'overview.bedStatus': 'बेड स्थिति',
    'overview.totalBeds': 'कुल बेड',
    'overview.occupied': 'भरे हुए',
    'overview.departments': 'विभाग',
    'overview.bedsAvailable': 'बेड उपलब्ध',
    'overview.bedsOccupied': 'बेड भरे',
    'overview.live': 'लाइव',
    'overview.staff': 'स्टाफ',
    'overview.available': 'उपलब्ध',
    'overview.status.normal': 'सामान्य',
    'overview.status.busy': 'व्यस्त',
    'overview.status.critical': 'गंभीर',
    'overview.bed.available': 'उपलब्ध',
    'overview.bed.low': 'कम',
    'overview.bed.critical': 'गंभीर',
    'triage.symptom.chestPain': 'सीने में दर्द',
    'triage.symptom.breathing': 'सांस लेने में कठिनाई',
    'triage.symptom.headache': 'तेज सिरदर्द',
    'triage.symptom.abdominal': 'पेट दर्द',
    'triage.symptom.fever': 'बुखार',
    'triage.symptom.nausea': 'मितली',
    'triage.symptom.dizziness': 'चक्कर',
    'triage.symptom.confusion': 'भ्रम',
    'triage.symptom.loc': 'बेहोशी',
    'triage.condition.diabetes': 'मधुमेह',
    'triage.condition.hypertension': 'हाइपरटेंशन',
    'triage.condition.heartDisease': 'हृदय रोग',
    'triage.condition.asthma': 'दमा',
    'triage.condition.cancer': 'कैंसर',
    'triage.condition.kidneyDisease': 'किडनी रोग',
    'triage.condition.none': 'कोई नहीं',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.triage': 'ட்ரையாஜ்',
    'nav.overview': 'மேலோட்டம்',
    'nav.doctors': 'மருத்துவர்கள்',
    'nav.patients': 'நோயாளிகள்',
    'nav.nurses': 'செவிலியர்கள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.changePassword': 'கடவுச்சொல் மாற்று',
    'nav.logout': 'வெளியேறு',
    'nav.about': 'அறிமுகம்',
    'nav.ethics': 'ஒழுக்கம்',
    'nav.regulations': 'விதிமுறைகள்',
    'auth.login': 'உள்நுழை',
    'auth.signup': 'பதிவு செய்',
    'home.portal': 'MediTriage பொது தளம்',
    'home.heroTitle': 'பாதுகாப்பான மற்றும் ஒழுங்குமுறை கிளினிக்கல் ட்ரையாஜ்',
    'home.heroSubtitle': 'இந்த பக்கம் கொள்கை வெளிப்படைத்தன்மையும் பாதுகாப்பான பணியாளர் அணுகலையும் வழங்குகிறது. உள்நுழைந்த பிறகே மருத்துவ தொகுதிகள் திறக்கும்.',
    'home.aboutBody': 'MediTriage மருத்துவமனைகளுக்கு AI ஆதரித்த ட்ரையாஜ் மற்றும் தீர்மான ஆதரவை வழங்குகிறது.',
    'home.ethicsBody': 'இந்த தளம் வெளிப்படைத்தன்மை, பாகுபாடு கண்காணிப்பு மற்றும் மனித மேற்பார்வையுடன் வடிவமைக்கப்பட்டுள்ளது.',
    'home.regulationsBody': 'அணுகல் அங்கீகரிக்கப்பட்ட பணியாளர்களுக்கு மட்டுமே. தரவு பயன்பாடு மருத்துவ விதிமுறைகளுக்கு இணங்க இருக்க வேண்டும்.',
    'footer.copyright': '© 2026 MediTriage AI. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    'footer.tagline': 'செயற்கை நுண்ணறிவு சுகாதார மேலாண்மை அமைப்பு',
    'common.backToDoctors': 'மருத்துவர்களுக்கு திரும்ப',
    'common.backToNurses': 'செவிலியர்களுக்கு திரும்ப',
    'common.backToPatients': 'நோயாளிகளுக்கு திரும்ப',
    'common.loadingDoctor': 'மருத்துவர் விவரம் ஏற்றப்படுகிறது...',
    'common.loadingNurse': 'செவிலியர் விவரம் ஏற்றப்படுகிறது...',
    'common.loadingPatient': 'நோயாளர் விவரம் ஏற்றப்படுகிறது...',
    'common.doctorNotFound': 'மருத்துவர் கிடைக்கவில்லை',
    'common.nurseNotFound': 'செவிலியர் கிடைக்கவில்லை',
    'common.patientNotFound': 'நோயாளர் கிடைக்கவில்லை',
    'common.active': 'செயலில்',
    'common.inactive': 'செயலற்றது',
    'common.found': 'கண்டுபிடிக்கப்பட்டது',
    'common.trySearch': 'தேடலை மாற்றி மீண்டும் முயற்சிக்கவும்',
    'common.tryAgain': 'மீண்டும் முயற்சிக்கவும் அல்லது ஆதரவை தொடர்பு கொள்ளவும்',
    'common.notSet': 'அமைக்கப்படவில்லை',
    'common.na': 'தகவல் இல்லை',
    'doctor.id': 'மருத்துவர் ஐடி',
    'doctor.department': 'துறை',
    'doctor.specialization': 'சிறப்பு',
    'doctor.experience': 'அனுபவம்',
    'doctor.years': 'ஆண்டுகள்',
    'doctor.license': 'உரிம எண்',
    'doctor.qualifications': 'தகுதிகள்',
    'doctor.contact': 'தொடர்பு',
    'doctor.unnamed': 'பெயரில்லா மருத்துவர்',
    'doctor.noQualifications': 'தகுதி தகவல் இல்லை',
    'nurse.id': 'செவிலியர் ஐடி',
    'nurse.department': 'துறை',
    'nurse.shift': 'பணி நேரம்',
    'nurse.license': 'உரிம எண்',
    'nurse.qualifications': 'தகுதிகள்',
    'nurse.contact': 'தொடர்பு',
    'nurse.unnamed': 'பெயரில்லா செவிலியர்',
    'nurse.noQualifications': 'தகுதி தகவல் இல்லை',
    'patient.id': 'நோயாளர் ஐடி',
    'patient.age': 'வயது',
    'patient.gender': 'பாலினம்',
    'patient.contact': 'தொடர்பு',
    'patient.bloodGroup': 'இரத்த வகை',
    'patient.recommendedDepartment': 'பரிந்துரைக்கப்பட்ட துறை',
    'patient.medicalInfo': 'மருத்துவ தகவல்',
    'patient.previousConditions': 'முன்னைய உடல்நிலை பிரச்சினைகள்',
    'patient.allergies': 'அலர்ஜிகள்',
    'patient.currentMeds': 'தற்போதைய மருந்துகள்',
    'patient.noConditions': 'நிலை பதிவு செய்யப்படவில்லை',
    'patient.noAllergies': 'அலர்ஜி பதிவு செய்யப்படவில்லை',
    'patient.noMeds': 'மருந்து பதிவு செய்யப்படவில்லை',
    'patient.guardian': 'பாதுகாவலர்/அவசர தொடர்பு',
    'patient.name': 'பெயர்',
    'patient.recentTriages': 'சமீபத்திய ட்ரையாஜ் மதிப்பீடுகள்',
    'patient.noTriages': 'ட்ரையாஜ் மதிப்பீடு இல்லை',
    'patient.department': 'துறை',
    'patient.symptoms': 'அறிகுறிகள்',
    'patient.riskScore': 'ஆபத்து மதிப்பெண்',
    'patient.unnamed': 'பெயரில்லா நோயாளர்',
    'patient.viewReports': 'பரிசோதனை அறிக்கைகள் மற்றும் ஆரோக்கிய பார்வைகள்',
    'patient.reportSub': 'முழுமையான ஆரோக்கிய அளவீடுகள் மற்றும் அறிக்கைகள்',
    'doctors.title': 'மருத்துவர் பட்டியல்',
    'doctors.subtitle': 'மருத்துவர்களை தேடி காண்க',
    'doctors.searchPlaceholder': 'பெயர், துறை, தகுதி அல்லது ஐடி மூலம் தேடுங்கள்...',
    'doctors.loading': 'மருத்துவர்கள் ஏற்றப்படுகின்றனர்...',
    'doctors.total': 'மொத்த மருத்துவர்கள்',
    'doctors.empty': 'மருத்துவர் இல்லை',
    'doctors.itemsPlural': 'மருத்துவர்கள்',
    'doctors.itemSingle': 'மருத்துவர்',
    'doctors.experienceSuffix': 'அனுபவம்',
    'doctors.licensed': 'உரிமம் பெற்றவர்',
    'doctors.noLicense': 'உரிமம் தகவல் இல்லை',
    'nurses.title': 'செவிலியர் பட்டியல்',
    'nurses.subtitle': 'செவிலியர் பணியமைப்பு மற்றும் நோயாளர் பராமரிப்பு',
    'nurses.searchPlaceholder': 'பெயர், துறை அல்லது ஐடி மூலம் தேடுங்கள்...',
    'nurses.loading': 'செவிலியர்கள் ஏற்றப்படுகின்றனர்...',
    'nurses.total': 'மொத்த செவிலியர்கள்',
    'nurses.empty': 'செவிலியர் இல்லை',
    'nurses.itemsPlural': 'செவிலியர்கள்',
    'nurses.itemSingle': 'செவிலியர்',
    'nurses.licensed': 'உரிமம் பெற்றவர்',
    'nurses.noLicense': 'உரிமம் தகவல் இல்லை',
    'patients.title': 'நோயாளர் பதிவுகள்',
    'patients.subtitle': 'நோயாளர் தகவலை தேடி காண்க',
    'patients.searchPlaceholder': 'பெயர், ஐடி அல்லது இரத்த வகை மூலம் தேடுங்கள்...',
    'patients.loading': 'நோயாளர்கள் ஏற்றப்படுகின்றனர்...',
    'patients.total': 'மொத்த நோயாளர்கள்',
    'patients.empty': 'நோயாளர் இல்லை',
    'patients.itemsPlural': 'நோயாளர்கள்',
    'patients.itemSingle': 'நோயாளர்',
    'patients.bloodType': 'இரத்த வகை',
    'patients.notSpecified': 'குறிப்பிடப்படவில்லை',
    'triage.title': 'நோயாளர் ட்ரையாஜ்',
    'triage.subtitle': 'AI ஆதரித்த நோயாளர் மதிப்பீடு மற்றும் துறை வழிமுறை',
    'triage.basicInfo': 'அடிப்படை தகவல்',
    'triage.medicalInfo': 'மருத்துவ தகவல்',
    'triage.vitals': 'முக்கிய அறிகுறிகள் (கிடைத்தால்)',
    'triage.guardian': 'பாதுகாவலர்/அவசர தொடர்பு',
    'triage.submit': 'AI ட்ரையாஜ் மதிப்பீடு செய்',
    'triage.patientInfo': 'நோயாளர் தகவல்',
    'triage.patientInfoDesc': 'AI ட்ரையாஜ் மதிப்பீட்டுக்கு நோயாளர் விவரங்களை உள்ளிடவும்',
    'triage.fullName': 'முழு பெயர்',
    'triage.fullNamePlaceholder': 'ஜான் டோ',
    'triage.age': 'வயது',
    'triage.gender': 'பாலினம்',
    'triage.genderMale': 'ஆண்',
    'triage.genderFemale': 'பெண்',
    'triage.genderOther': 'மற்றவை',
    'triage.contactNumber': 'தொடர்பு எண்',
    'triage.currentSymptoms': 'தற்போதைய அறிகுறிகள்',
    'triage.symptomsPlaceholder': 'பல அறிகுறிகளை உள்ளிடவும் (கமா, செமிகோலன், அல்லது புதிய வரி)',
    'triage.symptomsExample': 'உதாரணம்: மார்பு வலி, சுவாச சிரமம், தலைச்சுற்றல், வாந்தி',
    'triage.previousConditions': 'முன்னைய உடல்நிலை பிரச்சினைகள்',
    'triage.conditionsPlaceholder': 'முன்னைய நோய்கள், அலர்ஜிகள், அல்லது சிகிச்சைகளை எழுதவும்...',
    'triage.doctorsFollowing': 'பின்தொடரும் மருத்துவர்கள் (கமா பிரிக்கப்பட்ட ஐடி)',
    'triage.bloodPressure': 'இரத்த அழுத்தம்',
    'triage.heartRate': 'இதய துடிப்பு (bpm)',
    'triage.temperature': 'வெப்பநிலை (F)',
    'triage.respiratoryRate': 'சுவாச வீதம் (/நிமிடம்)',
    'triage.oxygenSaturation': 'ஆக்சிஜன் அளவு (%)',
    'triage.guardianName': 'பாதுகாவலர் பெயர்',
    'triage.guardianNamePlaceholder': 'ஜேன் டோ',
    'triage.guardianContact': 'பாதுகாவலர் தொடர்பு',
    'triage.processing': 'ட்ரையாஜ் செயலாக்கம் நடக்கிறது...',
    'triage.resultTitle': 'ட்ரையாஜ் மதிப்பீடு முடிந்தது',
    'triage.resultSubtitle': 'AI உருவாக்கிய ஆபத்து மதிப்பீடு மற்றும் துறை பரிந்துரை',
    'triage.riskLevel': 'ஆபத்து நிலை',
    'triage.riskSuffix': 'ஆபத்து',
    'triage.recommendedDepartment': 'பரிந்துரைக்கப்பட்ட துறை',
    'triage.clinicalReasoning': 'மருத்துவ காரணங்கள்',
    'triage.requiredTests': 'தேவையான பரிசோதனைகள் மற்றும் செயல்முறைகள்',
    'triage.viewPatients': 'நோயாளர் பதிவுகள் பார்க்க',
    'triage.error.required': 'அனைத்து அவசியமான புலங்களையும் நிரப்பவும்',
    'triage.error.symptomRequired': 'குறைந்தது ஒரு அறிகுறி உள்ளிடவும்',
    'triage.error.failed': 'ட்ரையாஜ் செயல்பாடு தோல்வி',
    'triage.success.complete': 'ட்ரையாஜ் மதிப்பீடு வெற்றிகரமாக முடிந்தது!',
    'triage.success.reasoningDefault': 'AI ட்ரையாஜ் வெற்றிகரமாக முடிந்தது.',
    'triage.risk.medium': 'நடுத்தரம்',
    'triage.department.general': 'பொது மருத்துவம்',
    'overview.title': 'மருத்துவமனை மேலோட்டம்',
    'overview.subtitle': 'நேரடி மருத்துவமனை நிலை மற்றும் வள கண்காணிப்பு',
    'overview.loading': 'மருத்துவமனை தரவு ஏற்றப்படுகிறது...',
    'overview.errorLoad': 'மருத்துவமனை தரவை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'overview.hospitalStatus': 'மருத்துவமனை நிலை',
    'overview.totalPatients': 'மொத்த நோயாளர்கள்',
    'overview.currentlyInHospital': 'தற்போது மருத்துவமனையில்',
    'overview.onDuty': 'பணியில்',
    'overview.freeBeds': 'காலி படுக்கைகள்',
    'overview.outOf': 'மொத்தம்',
    'overview.bedStatus': 'படுக்கை நிலை',
    'overview.totalBeds': 'மொத்த படுக்கைகள்',
    'overview.occupied': 'நிரம்பியுள்ளது',
    'overview.departments': 'துறைகள்',
    'overview.bedsAvailable': 'படுக்கைகள் காலியாக',
    'overview.bedsOccupied': 'படுக்கைகள் நிரம்பியவை',
    'overview.live': 'நேரடி',
    'overview.staff': 'பணியாளர்',
    'overview.available': 'கிடைக்கும்',
    'overview.status.normal': 'சாதாரணம்',
    'overview.status.busy': 'பிஸி',
    'overview.status.critical': 'அவசரம்',
    'overview.bed.available': 'கிடைக்கும்',
    'overview.bed.low': 'குறைவு',
    'overview.bed.critical': 'அவசரம்',
    'triage.symptom.chestPain': 'மார்பு வலி',
    'triage.symptom.breathing': 'சுவாச சிரமம்',
    'triage.symptom.headache': 'கடுமையான தலைவலி',
    'triage.symptom.abdominal': 'வயிற்று வலி',
    'triage.symptom.fever': 'காய்ச்சல்',
    'triage.symptom.nausea': 'வாந்தி உணர்வு',
    'triage.symptom.dizziness': 'தலைச்சுற்றல்',
    'triage.symptom.confusion': 'குழப்பம்',
    'triage.symptom.loc': 'மயக்கம்',
    'triage.condition.diabetes': 'நீரிழிவு',
    'triage.condition.hypertension': 'உயர் இரத்த அழுத்தம்',
    'triage.condition.heartDisease': 'இதய நோய்',
    'triage.condition.asthma': 'ஆஸ்துமா',
    'triage.condition.cancer': 'புற்றுநோய்',
    'triage.condition.kidneyDisease': 'சிறுநீரக நோய்',
    'triage.condition.none': 'எதுவும் இல்லை',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('meditriage_language') as Language | null;
    return stored && ['en', 'hi', 'ta'].includes(stored) ? stored : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('meditriage_language', lang);
  };

  const t = useMemo(() => {
    return (key: string): string => translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
